"use client";

import { useEffect, useState } from "react";

type DashboardData = { balance: number; approvedCount: number; videos: { id: number; title: string; category: string; status: string; createdAt: string }[]; referralCode: string | null; referralCount: number };

export default function Home() {
  const [view, setView] = useState<"dashboard" | "admin">("dashboard");
  const [showForm, setShowForm] = useState(false);
  const [sent, setSent] = useState(false);
  const [user, setUser] = useState<{ name: string; picture?: string } | null>(null);
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [adminPassword, setAdminPassword] = useState("");
  const [adminMessage, setAdminMessage] = useState("");
  useEffect(() => {
    fetch("/api/auth/me").then((response) => response.ok ? response.json() : null).then((currentUser) => {
      setUser(currentUser);
      if (currentUser) fetch("/api/dashboard").then((response) => response.ok ? response.json() : null).then(setDashboard).catch(() => setDashboard(null));
    }).catch(() => setUser(null));
  }, []);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const response = await fetch("/api/videos", { method: "POST", body: new FormData(event.currentTarget) }); if (response.ok) { setSent(true); setShowForm(false); } else alert("Teyit kaydı için önce Google ile giriş yapmalısın."); };
  return <main className="min-h-screen bg-[#f4f8fc] text-slate-950">
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-[#f4f8fc]/95 backdrop-blur"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 sm:px-8">
      <button className="flex items-center gap-3 text-left" onClick={() => setView("dashboard")}><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#1457d9] text-lg font-black text-white">H</span><span><strong className="block text-base tracking-tight">HaberKazanç</strong><span className="block text-xs text-slate-500">İçeriğini gelire dönüştür</span></span></button>
      <nav className="hidden items-center gap-1 md:flex"><button onClick={() => setView("dashboard")} className={view === "dashboard" ? "nav active" : "nav"}>Panelim</button><button onClick={() => setShowForm(true)} className="nav">Haber yükle</button><button onClick={() => setView("admin")} className={view === "admin" ? "nav active" : "nav"}>Yönetim</button></nav>
      {user ? <button onClick={() => fetch("/api/auth/logout", { method: "POST" }).then(() => setUser(null))} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold shadow-sm"><span className="grid h-7 w-7 place-items-center overflow-hidden rounded-full bg-[#dbeafe] text-xs text-[#1457d9]">{user.picture ? <img src={user.picture} alt="" className="h-full w-full object-cover" /> : user.name.slice(0, 2).toUpperCase()}</span><span className="hidden sm:inline">{user.name}</span></button> : <a href="https://haberkazanc.halkompleksi33.workers.dev/api/auth/google" target="_top" className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold shadow-sm"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#dbeafe] text-xs text-[#1457d9]">G</span><span className="hidden sm:inline">Google ile giriş</span></a>}
    </div></header>
    {view === "dashboard" ? <Dashboard openForm={() => setShowForm(true)} sent={sent} userName={user?.name} dashboard={dashboard} /> : <Admin password={adminPassword} setPassword={setAdminPassword} message={adminMessage} reset={async () => { const response = await fetch("/api/admin/reset", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: adminPassword }) }); setAdminMessage(response.ok ? "Yönetim verileri sıfırlandı." : "Şifre hatalı."); }} />} /> }
    {showForm && <div className="modal-backdrop"><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={() => setShowForm(false)}>×</button><p className="eyebrow">VİDEO TEYİTİ</p><h2>Gönderini teyit için yükle</h2><p className="form-intro">Videonu önce WhatsApp üzerinden gönder, ardından gönderi ekran görüntünü buraya ekle.</p><a className="mb-5 flex items-center justify-between rounded-xl border border-[#c9ddd2] bg-[#f5fcf7] px-4 py-3 text-sm font-semibold text-[#17663e] transition hover:border-[#25d366] hover:bg-[#ecfbf0]" target="_blank" rel="noreferrer" href="https://wa.me/34631355567?text=HaberKazanç%20video%20gönderimim%20için%20teyit%20istiyorum."><span><span className="mr-2 inline-grid h-6 w-6 place-items-center rounded-full bg-[#25d366] text-xs text-white">↗</span>WhatsApp’tan video gönder</span><span className="text-xs font-medium text-slate-500">+34 631 35 55 67</span></a><label>Google hesabın<input readOnly value={user?.name || "Google ile giriş gerekli"} /></label><label>WhatsApp gönderi ekran görüntüsü<input required name="screenshot" type="file" accept="image/png,image/jpeg,image/webp" /><span className="hint">PNG, JPG veya WebP ekran görüntüsü</span></label><label>Kısa not (isteğe bağlı)<textarea name="note" rows={2} placeholder="Videonla ilgili kısa bilgi..." /></label><button className="primary wide">Teyiti yönetici onayına gönder</button></form></div>}
  </main>;
}

function Dashboard({ openForm, sent, userName, dashboard }: { openForm: () => void; sent: boolean; userName?: string; dashboard: DashboardData | null }) {
  const balance = dashboard?.balance ?? 0;
  const remaining = Math.max(250 - balance, 0);
  return <section className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">KATKI PANELİ</p><h1>Merhaba, {userName || "Kullanıcı"} <span>✦</span></h1><p className="lede">Video haberini gönder, onaylandığında bakiyene 50 TL eklenir.</p></div><button className="primary" onClick={openForm}>+ Video yükle</button></div>{sent && <div className="mb-6 rounded-2xl border border-[#bce4d0] bg-[#effcf4] px-5 py-4 text-sm text-[#17663e]"><strong>Videon incelemeye gönderildi.</strong> Onaylandığında bakiyene 50 TL eklenecek.</div>}<div className="grid gap-5 lg:grid-cols-[1.4fr_.9fr_.9fr]"><article className="balance-card"><p>Mevcut bakiye</p><div className="balance"><strong>{balance}</strong><span>TL</span></div><div className="progress"><span style={{ width: `${Math.min((balance / 250) * 100, 100)}%` }} /></div><small>Çekim limiti için <b>{remaining} TL</b> daha kazanmalısın</small></article><article className="stat-card"><span className="icon blue">✓</span><div><p>Onaylanan video</p><strong>{dashboard?.approvedCount ?? 0}</strong><small>Henüz onaylanan video yok</small></div></article><article className="stat-card"><span className="icon orange">₺</span><div><p>Çekilebilir tutar</p><strong>{balance >= 250 ? `${balance} TL` : "—"}</strong><small>Minimum limit: 250 TL</small></div></article></div><div className="mt-8 grid gap-8 lg:grid-cols-[1.55fr_.8fr]"><section className="panel"><div className="panel-head"><div><p className="eyebrow">VİDEOLARIM</p><h2>Son gönderiler</h2></div><button className="link" onClick={openForm}>Yeni video →</button></div><div className="divide-y divide-slate-100">{dashboard?.videos?.length ? dashboard.videos.map((item) => <article key={item.id} className="submission"><span className="topic amber">▶</span><div className="min-w-0 flex-1"><h3>{item.title}</h3><p>{item.category} · {new Date(item.createdAt).toLocaleDateString("tr-TR")}</p></div><span className="badge amber">{item.status}</span></article>) : <p className="px-5 py-8 text-sm text-slate-500">Henüz video haber göndermedin.</p>}</div></section><aside className="space-y-5"><section className="panel payout"><p className="eyebrow">PARA ÇEKME</p><h2>250 TL’ye ulaşınca</h2><p>IBAN bilgini ekleyerek ödeme talebi oluşturabilirsin. Talepler haftalık işleme alınır.</p><button disabled>Ödeme talebi oluştur</button></section><section className="note"><strong>Referansla kazan</strong><p>Bağlantını paylaş; referansınla ilk kez giriş yapan her kişi için hesabına <b>10 TL</b> eklenir.</p>{dashboard?.referralCode ? <a className="mt-3 block break-all text-xs font-semibold text-[#1457d9]" href={`https://haberkazanc.halkompleksi33.workers.dev/?ref=${dashboard.referralCode}`}>https://haberkazanc.halkompleksi33.workers.dev/?ref={dashboard.referralCode}</a> : <p className="mt-2 text-xs">Google ile giriş yaptıktan sonra referans bağlantın burada görünür.</p>}</section></aside></div></section>;
}

function Admin({ password, setPassword, message, reset }: { password: string; setPassword: (value: string) => void; message: string; reset: () => void }) { return <section className="mx-auto max-w-2xl px-5 py-8 sm:px-8"><p className="eyebrow">YÖNETİM ALANI</p><h1>Yönetim paneli</h1><p className="lede">Bekleyen video teyitleri ve kazanç kayıtlarını buradan yönetebilirsin.</p><section className="panel mt-8"><h2>Verileri sıfırla</h2><p className="mt-2 text-sm text-slate-600">Bu işlem video teyitlerini, kullanıcı bakiyelerini ve referans kayıtlarını kalıcı olarak temizler.</p><label className="mt-5 block">Yönetim şifresi<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Şifre" /></label><button type="button" className="reject mt-4" onClick={reset}>Tüm yönetim verilerini sıfırla</button>{message && <p className="mt-4 text-sm font-semibold text-[#17663e]">{message}</p>}</section></section>; }