"use client";

import { useState } from "react";

const submissions = [
  { title: "Yerel üreticiler için yeni destek paketi açıklandı", category: "Ekonomi", time: "Bugün, 10:42", status: "İnceleniyor", tone: "amber" },
  { title: "Şehir merkezinde ulaşım düzenlemesi başladı", category: "Gündem", time: "Dün, 16:18", status: "Onaylandı", tone: "green" },
  { title: "Genç sporcular turnuvadan madalyayla döndü", category: "Spor", time: "12 Eylül", status: "Onaylandı", tone: "green" },
];

export default function Home() {
  const [view, setView] = useState<"dashboard" | "admin">("dashboard");
  const [showForm, setShowForm] = useState(false);
  const [sent, setSent] = useState(false);
  const [signedIn, setSignedIn] = useState(false);
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); setShowForm(false); };
  return <main className="min-h-screen bg-[#f4f8fc] text-slate-950">
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-[#f4f8fc]/95 backdrop-blur"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 sm:px-8">
      <button className="flex items-center gap-3 text-left" onClick={() => setView("dashboard")}><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#1457d9] text-lg font-black text-white">H</span><span><strong className="block text-base tracking-tight">HaberKazanç</strong><span className="block text-xs text-slate-500">İçeriğini gelire dönüştür</span></span></button>
      <nav className="hidden items-center gap-1 md:flex"><button onClick={() => setView("dashboard")} className={view === "dashboard" ? "nav active" : "nav"}>Panelim</button><button onClick={() => setShowForm(true)} className="nav">Haber yükle</button><button onClick={() => setView("admin")} className={view === "admin" ? "nav active" : "nav"}>Yönetim</button></nav>
      <button onClick={() => setSignedIn(!signedIn)} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold shadow-sm"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#dbeafe] text-xs text-[#1457d9]">{signedIn ? "AY" : "G"}</span><span className="hidden sm:inline">{signedIn ? "Ayşe Yılmaz" : "Google ile giriş"}</span></button>
    </div></header>
    {view === "dashboard" ? <Dashboard openForm={() => setShowForm(true)} sent={sent} /> : <Admin />}
    {showForm && <div className="modal-backdrop"><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={() => setShowForm(false)}>×</button><p className="eyebrow">YENİ VİDEO HABER</p><h2>Videonu incelemeye gönder</h2><p className="form-intro">Onaylanan her özgün video haber için 50 TL kazanırsın.</p><label>Video başlığı<input required placeholder="Kısa ve açıklayıcı bir başlık" /></label><label>Kategori<select defaultValue=""><option value="" disabled>Kategori seç</option><option>Gündem</option><option>Ekonomi</option><option>Spor</option><option>Teknoloji</option></select></label><label>Video dosyası<input required type="file" accept="video/mp4,video/webm,video/quicktime" /><span className="hint">MP4, WebM veya MOV · En fazla 2 dakika</span></label><label>Kaynak bağlantısı<input required type="url" placeholder="https://" /></label><label>Video açıklaması<textarea required rows={3} placeholder="Videoda ne olduğunu kısaca anlat..." /></label><button className="primary wide">Videoyu incelemeye gönder</button></form></div>}
  </main>;
}

function Dashboard({ openForm, sent }: { openForm: () => void; sent: boolean }) { return <section className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">KATKI PANELİ</p><h1>Merhaba, Ayşe <span>✦</span></h1><p className="lede">Video haberini gönder, onaylandığında bakiyene 50 TL eklenir.</p></div><button className="primary" onClick={openForm}>+ Video yükle</button></div>{sent && <div className="mb-6 rounded-2xl border border-[#bce4d0] bg-[#effcf4] px-5 py-4 text-sm text-[#17663e]"><strong>Videon incelemeye gönderildi.</strong> Onaylandığında bakiyene 50 TL eklenecek.</div>}<div className="grid gap-5 lg:grid-cols-[1.4fr_.9fr_.9fr]"><article className="balance-card"><p>Mevcut bakiye</p><div className="balance"><strong>150</strong><span>TL</span></div><div className="progress"><span style={{ width: "60%" }} /></div><small>Çekim limiti için <b>100 TL</b> daha kazanmalısın</small></article><article className="stat-card"><span className="icon blue">✓</span><div><p>Onaylanan video</p><strong>3</strong><small>Bu ay +2 video</small></div></article><article className="stat-card"><span className="icon orange">₺</span><div><p>Çekilebilir tutar</p><strong>—</strong><small>Minimum limit: 250 TL</small></div></article></div><div className="mt-8 grid gap-8 lg:grid-cols-[1.55fr_.8fr]"><section className="panel"><div className="panel-head"><div><p className="eyebrow">VİDEOLARIM</p><h2>Son gönderiler</h2></div><button className="link" onClick={openForm}>Yeni video →</button></div><div className="divide-y divide-slate-100">{submissions.map((item) => <article key={item.title} className="submission"><span className={`topic ${item.tone}`}>▶</span><div className="min-w-0 flex-1"><h3>{item.title}</h3><p>{item.category} · {item.time}</p></div><span className={`badge ${item.tone}`}>{item.status}</span></article>)}</div></section><aside className="space-y-5"><section className="panel payout"><p className="eyebrow">PARA ÇEKME</p><h2>250 TL’ye ulaşınca</h2><p>IBAN bilgini ekleyerek ödeme talebi oluşturabilirsin. Talepler haftalık işleme alınır.</p><button disabled>Ödeme talebi oluştur</button></section><section className="note"><strong>Ödül kuralı</strong><p>Yalnızca kaynak gösterilen ve yönetici tarafından onaylanan video haberler için 50 TL kazanırsın.</p></section></aside></div></section> }

function Admin() { return <section className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><p className="eyebrow">YÖNETİM ALANI</p><h1>Video onay kuyruğu</h1><p className="lede">Onaylanan her video için kullanıcı bakiyesine otomatik olarak 50 TL işlenir.</p><div className="mt-8 grid gap-5 md:grid-cols-3">{[["!","orange","Bekleyen video","12","Bugün 4 yeni kayıt"],["₺","blue","Bekleyen ödeme","8","Toplam 2.000 TL"],["✓","green","Bu ay onaylanan","86","4.300 TL ödül işlendi"]].map(([icon,tone,label,value,note]) => <article className="stat-card" key={label}><span className={`icon ${tone}`}>{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></article>)}</div><section className="panel mt-8"><div className="panel-head"><div><p className="eyebrow">İNCELENECEKLER</p><h2>Video haber başvuruları</h2></div><button className="link">Tümünü görüntüle →</button></div>{["Mahalle pazarında üretici günleri başladı", "Yeni eğitim desteği başvuruları açıldı", "Kıyı temizliği için gönüllü çağrısı"].map((title, i) => <div className="submission" key={title}><span className="topic amber">▶</span><div className="min-w-0 flex-1"><h3>{title}</h3><p>Gönderen: kullanıcı#{204 + i} · Video ve kaynak eklendi</p></div><div className="flex gap-2"><button className="reject">Reddet</button><button className="approve">Onayla +50 TL</button></div></div>)}</section></section> }

